// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// todos
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	// users
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) (int64, error)
	DeleteTodosByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	GetTodo(ctx context.Context, arg GetTodoParams) (Todo, error)
	GetTodosByUser(ctx context.Context, userID uuid.UUID) ([]Todo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
