POST http://localhost:8000/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY0MDIxNDQsImlhdCI6MTc4NjQwMTI0NCwidG9rZW5fdHlwZSI6ImFjY2VzcyIsImlkIjoiNmE3YTUxZGNhYWEyZDQ0MjkyOTAxNzY2IiwiY3VzdG9tZXJfaW5mbyI6eyJpZCI6IjZhN2E1MWRjYWFhMmQ0NDI5MjkwMTc2NiIsIm5hbWUiOiJBeml6IEFsLVNvdWZpIiwiZW1haWwiOiJheml6QGV4YW1wbGUuY29tIn19.XPGck9SqTnih321KMgtpL4CDse2lWtU1C4LvY6rXzxT-NGvwuFbuQsJRNZir57WKAr1tlTf-_B-DgIMZfj8Nnz4e-1V0_WYMQzcWGTCqqIw0FZYlwuBJJiu0qT6_tnKSWF9nmlUDVVb2PWrhISMfcPBRkVck5ui-gcXIjfEsHgCZk1xmxtWqUw9kojuG8Sbc1lS5xucGamztpZnf2yofgamiHY9Jl-DR_7T2P8NSlM4ENP6LFsCk0CWNsQTdpbgYFqViDLUwf73Br9WLM2wZqmCoG65hBVTjUAAb6fpd-QoyARenhHx-9KZaMindufPL0D0U5TE_E6wUB06Zs5NbiaY6M1_F1nTVWwfrjQdZm-A17sglOhBsBvy2U3P4K5m_ufD-HiRYul-CLLQ1Huuk1W_EcjU03DmfWBDXb9_2wNMQ0VAN2DG9dOuQ2oxqZBW6uQLE0PEIqN7Xcgz5DwmSyXwRLZHIg3ckoG1gjpyRcOQyk_QJoYFyU7MhwUz3QoAoiEro0Mu00xfkoLU68DydDqTp0VxN3OYrt_rMF1NcQ0CrlzoQ9rmOLjM4qrFwsNvwnCMtsigI3vgiCcVkgEeFR_3-i_wQok4EFqt5DddipX66Re32CBSxyO1FiIo1HCSdVO1Vo1iaQaKvpohetXPEEEOy8J0Zuij0IuGBmSj4urg

// eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODcwMDYwNDQsInRva2VuX3R5cGUiOiJyZWZyZXNoIiwiaWQiOiI2YTdhNTFkY2FhYTJkNDQyOTI5MDE3NjYiLCJjdXN0b21lcl9pbmZvIjp7ImlkIjoiNmE3YTUxZGNhYWEyZDQ0MjkyOTAxNzY2IiwibmFtZSI6IkF6aXogQWwtU291ZmkiLCJlbWFpbCI6ImF6aXpAZXhhbXBsZS5jb20ifX0.ClSliFxiH8lBb4vUBVAAmUdF9bk6R-r1nQmSrmOVJ01RD0iQCNDiLnwMOBPddfBosskmjFZtvewLumpyIfp3LVrOdM_Ad2yFts5jNIq09saCA-U1W7j0mz9U5HCmSQPdr_sSpFU4jTbmYN25Eqgcca93AQL8UglC3sJbpcQSvbYusyeArjNATed5V2_R5-HyqZhNU5q3V2jG41nAL2X76sEHBkSgLhS0Xy1mQdH_Hyvz1Vm_dd1iykIy9eZQ2TMb8v3wDiVaBb0aTLax05c0tRNevXV0QKudKZZB__7aT-NXzuxlS_ijQCFJW6yM37GoZUU0si4tGsQdbjS4Cw3xCTFxmhXaa9DwxDj1Z1PyeZjlSRrAW5dZUxTUCGZzDNz3fxM4ynPyO-diwHPXrXLaRrYHx-fefpGr7Ypnr5hkYHIhKwLZJIB6kAzDFvCzkY2dyvrWdXOSYJ4K6SFgpMwf1xFHclyRpYKmlMaeBgkAHezPq7vVsn75EIQlCUgGIdBW5rbjfGuQ_1vkizb3TvhxsXUejVdNQ0LBImdqV5Lc2wSKILLo2Z6xbq-m4LpNFddoZklvIYP435jg834sTmIAkFcaq3d_bBxXoYoyH8_GOJz3t3G3Ln1nOroOxaWNvEpjdB-GO_POo6Zl_SvDQaR6AiJpumqP55lCKbEC9hmb5go