POST http://localhost:8000/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODYzMjUxOTEsIlRva2VuVHlwZSI6ImF1dGhlbnRpY2F0ZV9vbmx5IiwiSUQiOiIiLCJDdXN0b21lckluZm8iOnsiaWQiOiI2YTc5MjRlZTJhNWE0ZmM3OGU3OGNlMGIiLCJuYW1lIjoiQXppeiBBbC1Tb3VmaSIsImVtYWlsIjoiYXppekBleGFtcGxlLmNvbSJ9fQ.WcR9d4uaSqNQllpM2Qfl-9jYeaZSbqPZz346N2xu9h56L1UcI4fZfOctIh2GO1cVtrnht63tGxNvuURmy3jtPH4t-zbSiMmHPVs08QZvP26YsKOvTHIaP554PTn3gqkfQCRSZNn1-bLbZafTjAj7zXAtSM8vD_DikgpNdrWSCia39Vi6Mb63WY3hA9e4fNP_SPJjkAWfVvLRqXH0DrmSpC-pkfNx5_CE3dotTu1vca4PaKQhQWMQspxWk0PnTlymbO9iTaD0Q2NH-dk1bSf3kPhW55aYkdZ1WS_ysjZfJNM4iNK__xNyteVbGp3Rm92dQCYE3wSbJvrp99GHuuFSKFUAprd-Fmd7drJkD3tJEQOsi9mozev2dOCwsMEdVn5hiJNRz7R6-bI69j9eZ8S-X_szpD9aejHO0E4zFTGnYs__0lpj4-lBPhzFmL6s2O5rJm2yBZZAUPQ676PHYa8Z7YIMQNJlhO1c6tBCVU-cdh9zBuvARTUKV4E6TarVjtmW9dA-sb7sadXr65B6U5j5dllTLt7w3GFNXrvzDc_f_G4GLgOC_dG5RpaV3PDX6O9VViwAB_8nEwZmO-5YBK-rVSf4J_anQuT_6b9kvKFm4cemx1oh5_2VjwEvv-cRPoJQEpJUtxqC_sTpq4iL8-7if4-ofFCD2TAubvd-qZLz49I

// eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY5MjYwMDMsIlRva2VuVHlwZSI6InJlZnJlc2hfb25seSIsIklEIjoiIiwiQ3VzdG9tZXJJbmZvIjp7ImlkIjoiNmE3OTE5MzM5NWJlYzYyNmIzZjFiZjg5IiwibmFtZSI6IkF6aXogQWwtU291ZmkiLCJlbWFpbCI6ImF6aXpAZXhhbXBsZS5jb20ifX0.XGvayuSUXKAut2e4m7VoHlbAxZqJs6vEXmMh8mG8mWNT-Zk_iVrXkVFhXar0csau6oBH02u1FJXJc9Fyu57XBacf3JGO1t4TqZaiqjtCVAVxuE91ZAM00wK6T1i3h6wvnULSaxlYgk9ODaJ34HOuZXifNo2dNvlhO_ZV-DY-OBcdlRzcAZZEXQNgaWZieOAtzx65mlZBYE4tAS9MfqLbq05DUTLHkzcEn0OBGlqktod2zBkCTX4OabXy06ivGvGsZ7bIM6pA5BDMw34PeJl9_ssydx34DouGzNVUH_82x80R036ztZumhiC0CoF0f1XNVBvTB747Vh1gK635D9kG9aVhOfjSN61k1blci-ndoXbc2z4czLJQFXk5FsFl5GwvVsZ-1xxo6M8gwUGNQtCwxfi-V7rz7vccy-XZ5gLtwN8LKBbMQaZCu1OjyuGV7bt57eAaY34RBiB6CHd5lFsosCkw6Ju0yBDwraQyvhndp3W8dQsCf0jdtjAmHzql0XTXIc4msLotuL0nBb2a1xfFbYEmnXuGjVc9XkMJ_Vhl8RckORiZlA4YEboRCSuaGQssKagfmALrKmnzeNkW1VwhU-fg_1hyW19arnMKYnTMOLxriLETaCA9bn06IV2bploBGIsNMdljD-q3Abq2JiL0KYFlbLVZnVa7BkRzf-T85XU