POST http://localhost:8000/refresh-token HTTP/1.1
Content-Type: application/json

{"refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY5MjgwMTUsIlRva2VuVHlwZSI6InJlZnJlc2hfb25seSIsIklEIjoiIiwiQ3VzdG9tZXJJbmZvIjp7ImlkIjoiNmE3OTIxMGZjMmMyYTViOTZmZWIwY2RkIiwibmFtZSI6IkF6aXogQWwtU291ZmkiLCJlbWFpbCI6ImF6aXpAZXhhbXBsZS5jb20ifX0.O10E-NT1WarCSj_rlWKDgi0it24tGm1cnGxzmPzDC5gxiAkzMRG63jZhcLcZOqK4SX1-u3qEvjv6O08cj9oXi7KVvYciR8_CtR56jkYjxd5y7u-1rbTv5y90MynFvk6HO-368soNUrx67AyvyGP_bOPxCsGjNTFrv6eVt_W0S6skb8vf-xPBWI7mxS5_4vdwJ8jcNYv3W7HGBO_NuF2capKs1-MwUYS3pOj-I1K_g1ANJzaq1Ywao4VDeFc3Y86tN0LUnQk61XW6ukOoEz2ezWLn6MACa8Wl3wMk8oR3IA08GC4q7KaiPARxkhoXUtFeSjiGmROkeMkEnhHxcnzWuS531kvVDmzEMl76bh_ruIVDKXVreRrvMAE-XVy90vtB-SL3zTlUnEvpFuhaQFbCrbcV1IdRcq4SPfz8XM-Y9Cn1j_MqrYZyglZbr4DX7if7nTtfhHrC9Mgk4dQe9v13VGbfTn3V35sdRR2i_gApyDkXNpiEsKxZnuudCv_Gp9gt3REvPlkhiDORKZRvDP0B_-LHuTbMgtU6DWWaYOfoSyGZgDSYn70jygbtQgHc5-zyNJRqTp_lA6E-X5Dupd44IrzQPQSvC4_4jYI-90oXOo8mkjj0g-ZlnpxVTDMExswR7tjvHR5Qs9uohg-wRQBV3-buPtrLvGbc6CLKlsGxx8w"}
