POST http://localhost:8000/refresh-token HTTP/1.1
Content-Type: application/json

{"refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY5MjUzMjMsIlRva2VuVHlwZSI6InJlZnJlc2hfb25seSIsIklEIjoiIiwiQ3VzdG9tZXJJbmZvIjp7ImlkIjoiNmE3OTE2OGIwY2Y1NzAyMGIyMDkxOWQ0IiwibmFtZSI6IkF6aXogQWwtU291ZmkiLCJlbWFpbCI6ImF6aXpAZXhhbXBsZS5jb20ifX0.osSji5xEdm9FUC0jTfgL4javZk41IhHtDi1b4_T140j6U-JNRcmRtYXLNvcsTmel3_HPKUSsuTXASs16f8BFlpeiLa9ZvFJKhnfFGxREXO_PTLxzhc-QG6OACkgwKOGcQBnAyLvQl_TEVUrq73KPbI6BDG4yFE-GSptCTYi7hBqs61qaijOkyR0o9NSkxDqYHW0pfISTFk5mixxLBhB-gfWfqI9_7zZUVv24TFwOeckz7bcXoInL5cqOghC0F8Pwg9cMNzCMoe-Esqyxjd6K44wMoLzkCgITNY64xqGKQrRYKQe0nkiJb629WvAdQzr7ueJVQAFc5llDvYxA6XLsSdhPdWqgrQPu7XhSyrh_GGZ665f6t9_Uali5fbbATkO51OtspIwBc-VmAkBGObsrO-YNcrZ7f_HrgwRts0P5ha3TSGWr5FMwALhoc_CgBsyLSNNT0N-V8zd8S8LKq3sx76I7Rj876Dm4iyIPnFvSayiNUHrYXAzh_kZfcB1yPSM9Ua9Er69Fyxc0UVhSGdGq3JL_I2ulHCriUrR34zE9AU70S5sqFL7yXrds7DFOyyN5raTdhfc5HtrdrUXi8EYoKxj5FrpKAVgvTqTG9_0FnHt1u9LD4rqbaca1ay_uzlRa1_qrT6gg_6yPsJMMOy4LFrF3pvdcvNe_D4V_pniiyec"}
