POST http://localhost:8000/refresh-token HTTP/1.1
Content-Type: application/json

{"refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY5ODIzMTUsIlRva2VuVHlwZSI6InJlZnJlc2giLCJJRCI6IjZhNzlmNTJiNGIyNTEzNWM2MmJiZGMxNyIsIkN1c3RvbWVySW5mbyI6eyJpZCI6IjZhNzlmNTJiNGIyNTEzNWM2MmJiZGMxNyIsIm5hbWUiOiJBeml6IEFsLVNvdWZpIiwiZW1haWwiOiJheml6QGV4YW1wbGUuY29tIn19.URmmZOp70aCnby0AZdN0Ffqu95jNKnICGfOYcLM7VQpXPgkOSWsS9JyQPh4rMdc9oRUGFVZaPDEWPD60mvD2Ya9goOvWY6iFrRUq8PI4o5M1lgqIjyyXIykZ_8kOhkklKA6hO6wZur0oUd-pZA0jeFa55zAJeckxAMwHDvpkW1sbhvwVyPqlhf6pDJ6Cn7cM6IDNaV_WsXhp6hpCHGNtXU3vi1vtrsN5DHuOwR8JYiNyXvDZVDzRqymRT-6Dya9dMT8AYa36lB6XTecWnQmDYpfQGDQQukotDtCCrZfYGNtux5xHoVtL0n6g2uBAxug4WP5JWLawh_7rP80O9e6fZzhGK_dO89LYxFX9f46GCd6jWkHq6lRL8FvjTPb1-jtuOiwBjgG2Fbv2itnXJ7OiZeho4x8UKPp7L7mGQd92PCiRzibxDg577lKiDndRV2AWEOTjrGluhwjGTwnNLZxDLesZ6sIgPYnPMNP1wp01UDUyhAMT0gfYbIcS3AUBpj_UsuSB9RcYzrnTUFpnkA9_EfFkqWI3sfF5_Z-EDkjQNvJIQeyJyMciOHT5MDBYKWva9fY2UISGv1Ynka8f-C3WwOWAhn2-ZbQ426OHO1ke0AgqdJU16HDcu41pTs5ybHQe20Lyk4dEvvzgtcyIdmL-8L8El1GN7uZiQmZS4s58Qu8"}
