GET http://localhost:8000/todos/6a7914215b6be4644a7a1280
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODYzMjA2ODcsIlRva2VuVHlwZSI6ImF1dGhlbnRpY2F0ZV9vbmx5IiwiSUQiOiIiLCJDdXN0b21lckluZm8iOnsiaWQiOiI2YTc4ZjRjNzRkNWNlNzljNTkyNmE1NzUiLCJuYW1lIjoiQXppeiBBbC1Tb3VmaSIsImVtYWlsIjoiYXppekBleGFtcGxlLmNvbSJ9fQ.eRAepea1js7I0ZmjNtpen8ByfNwc_b4Pcgv3JErrToLi7C8-suWGQNUD06iTkWtFA2Lp1cOSXoXNxifGNm1PVeM8uUDVwVb4OUpvTuTQMttqL_vxtziFhnq0t52jwCOQBl-lYv0fLJAB5ffbSUa9wIb1hLroqUqSceaSAf1n9JaAv52TWVn1y_3Y5RjIlva4hg2DJOA9Dw2Tcb5moLg97IAonjwzscEwEqU55q5xDAHER1onIaA51sFciATTqWGbhKbObRi5TLJttbnRb1Q1bzvWaEl6nvqbsPWPeDfQM0Gmgw8nMpP6RaDp9YigwtE6lgOH1smxGU27VIv9Euk0CuQPF4mvoBO1MIApBh_Y7jQ7cZIP9ZE6q3bPiO8gqrCrdGRqZP6tbLV0hB8Tma_SBp9ssT96l_fysEMjNavBd_5fyGEDzgjhDMYFg4kUOCYvZGREBrZuMBIF7BUUsxwDviT1InZ9bq6subNfZ1NYEEPLttqFlBGODhU-z-hHlqExpxKzwo9Jyuc_7SVEkqoWg9XIw1DeJ0vedl2uJDtnDZGfNB5KR6l_dZuaSB3JueKyBymTxy_YiMG3vepVZ8bbF8BIwJ5VSP_ANJcbjZ4c127j11ulzvWRSRFXhyzGTVpbPJNbRakoCF9YAYjBDYLv8JvqySFdKhmzOCr6Ov6CMBc
