GET http://localhost:8000/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODYzMjEzMzIsIlRva2VuVHlwZSI6ImF1dGhlbnRpY2F0ZV9vbmx5IiwiSUQiOiIiLCJDdXN0b21lckluZm8iOnsiaWQiOiI2YTc5MTYzMDBjZjU3MDIwYjIwOTE5YzciLCJuYW1lIjoiQXppeiBBbC1Tb3VmaSIsImVtYWlsIjoiYXppekBleGFtcGxlLmNvbSJ9fQ.DuYzAu0csOKvfTJNWgtiTm-S9K1mSZwPPA3gESPaSrB1_UIHVGMeHeO7JkXINMAo5Jn68oZ8fGvhIn3ylXtgtuRiU5LVh1gxtpN0K8-rfNi00Dvo7Ky6_LU8xqz7mvOhC7fo3FerXW-a46hzG-6mpspEVeP_98p3IMDDc2Jhl-zkcK9kKqzlD8cSgvAHkWe4Dm9ORZKzdK2KsmlyUZRev6hI_6GrKpNjElxZUUz1uD61x5X8Jnhr92X4ezyhL6Pa_S_CF4JgIdg1Uh1WCWj27MhdL9xhABjLZX51zuFYFC0YM6rWy_arVeHhDWyxrSieJJHRz3A5ZbqzPqH2c0t8AW3AokLA3vst-IKqauofOngnV6rNdGZZD5RYc_jm1mmLTk6RhQulmo4GDY5AniAa-L-zxV5MAtrgOhqcf7Xyt-H2ERpqMlJxG4Cz8NP_s3TEgMJbDs5YGFnGFy8hBXXz2oVsydtI-89qDFZsuYUM3Nc2yFux3KMvZpAdhWnHZFL3s3yCsdAvNmg1If6oz1LvQz8u5M2zk2EP0ybGWrbOxJ9ocJ996RTzS43BuuCmqP8kdev-2uC6i_IXGlsdUImts37BkpxakxG0pa5OzMuaqT-feggo90qS-oavJ7NpdboPFermnHVvf-RAkxBST-apMUGoOQHrO5Eh5sOWHaebn1c