DELETE http://localhost:8000/todos/6a79182be38d391b3ab1080a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODYzMjQxMzAsIlRva2VuVHlwZSI6ImF1dGhlbnRpY2F0ZV9vbmx5IiwiSUQiOiIiLCJDdXN0b21lckluZm8iOnsiaWQiOiI2YTc5MjEwZmMyYzJhNWI5NmZlYjBjZGQiLCJuYW1lIjoiQXppeiBBbC1Tb3VmaSIsImVtYWlsIjoiYXppekBleGFtcGxlLmNvbSJ9fQ.g-ptfzLreCP8gIlCDPzeDDh4vYgGOIeE_BzhwPRXEnaw6fNSSHW8GXeINeO0TGgSfpioFJOuSiPUi0lc_-9AF4t3luWAzu30GI6zXMeCot7xeQLX4R1RLO7EC7Sx88WoptjW0Xc6xMQeEjZenGAq6Dc9V_bumZOcBQEpajIR2x5Xj16u4s4O_4qNXhtFrvtIjCMCqDu4xvMw9nwBrvIFTEPZzYnqSudZ1Wps422D6qY3AbjJeOweDMjQIiBXJO3V8bhsw3itcJmecC7bojN-YVSB10eC3VaW9Diku2jfkTqXYxurXLhpB4a3e6WgSu-6mtwvAedMPYtOgomKvjeKJOQb2xkgpKA-CAy11iQ5hcrtXN2CexIdSvtjMEXpEhIBAMGZUibA66KfU4CmMSqOI9OB5o3GRimhRqdRBn2lzSVQi6NApdA6YY8edJWksjuIZWanjPpBPhuwFpzKZgIlld9C9GifNvck1LAhdzV7wnil-J9j-8IsYrM3A-j5bac9XmfxaIuL0QtJxQtO3NrY3IurRp2XqlF3Mfdmm4EepsunISeckLsP7WVMLSkFsWKRMKkvI445wpxzVpKBg-HvCUzmmJpZqDi75Aw0GGUSlVUZPVMQBmlmLPR4NtRILAILgc-K3rs-YEtfC1sqcxrTg_FTQogKGnyVfM_KF9ZgS9c
