PUT http://localhost:8000/todos/6a791828e38d391b3ab10808
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODYzMjE3OTksIlRva2VuVHlwZSI6ImF1dGhlbnRpY2F0ZV9vbmx5IiwiSUQiOiIiLCJDdXN0b21lckluZm8iOnsiaWQiOiI2YTc5MTgwM2UzOGQzOTFiM2FiMTA4MDciLCJuYW1lIjoiQXppeiBBbC1Tb3VmaSIsImVtYWlsIjoiYXppekBleGFtcGxlLmNvbSJ9fQ.Xh8Q07RtRxg4sHhMXSXtGexi3a41h6g_IbT-xTU3FkoSsjX5jOIumE3c5ssuN6j32Qp0YFVQMbmfgKIJzJ79Djrm_p_b6VAojCWk97pmwdAhBtITJCKsDyXneWG2piL4-45_xULKTWTtuqZYVZH-OcXbXLxllj0ifyq_Lqjje1SeufsdgnRcpHtjnQXMwdYtgx7WqS-VShjHZrQ9yfymEiKDvsbyIsxmGNcktbemj3Bz3p_WCeZU4-BU6vMKT3V2Oc1ziYpNxbJXkFxA5QFO5jY2bjvfkBPqvWL2qRsvVuGw8i-5AH8HiLB4zOagPOBJq8OSL-EHiJgRTBMiPDqBdTYEpChzo1TPGGhxl3seg0fwS2_lAEuIoyqUyVYJXWaubv9jEcsPWHMR99qGhSND2SrAB_8uuYNzxSk8yAGTJaeferXvrZxy-_FoXWTXd7HvjryVIbXwzJRnsUMVfkciW-dWRnQFg4VlykwKXoJen6KRc-aFUXxZgIDMqkyI-aXRvC9oKu-bPlF8xPQdMIIPwjQ9THmVW9_0tfkb2NDzQ2I1Nrfum-JmCdfLr4ZHJrx2jYweHyUnx7D8tmy6dABwErpmOSvk2TW3WIyiFPFX6uEpVDHrgPSpsTW7mWwHVFWjf_L9-X8AQ-OiH_3zB8TLZn2_bo4hV0pJcA4RLS12L8E

{"completed": true}

# {"title": "Testing golang PUT Methods"}
# {"title": "Testing golang PUT Method", "completed": true}
# {"title": "Testing golang PUT Methods", "completed": false}
# {"title": "Testing golang PUT Method", "completed": null}