DELETE http://localhost:8000/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODY0MDMwMzUsImlhdCI6MTc4NjQwMjEzNSwidG9rZW5fdHlwZSI6ImFjY2VzcyIsImlkIjoiNmE3YTU1NTdlOGY0OWE5NTIyMWJhMzNkIiwiY3VzdG9tZXJfaW5mbyI6eyJpZCI6IjZhN2E1NTU3ZThmNDlhOTUyMjFiYTMzZCIsIm5hbWUiOiJBeml6IEFsLVNvdWZpIiwiZW1haWwiOiJheml6QGV4YW1wbGUuY29tIn19.Yp8G2m-JfLekwLzDFi0EEUfZchwpK6gei8JK1fBOvTwksiycOJ2sy4ndFnqq92xCl7OKxrBX0OgrcC4RSafB28any8U2XuhGmCqCX8BLN6QudiGXF4y5sZHkGCGJgmIEz5tFAfrFjja-k7N7fG9mcvuefGOWjR_bClgZMHzC0mLKeJE4Bi7eTrmBJQ1RwvCS2m05w1QiMAFmYq2LM1Zps2cyBFvY_Y3AUJua0gl33SHz6VaUPXrOEZEJAnuGb2x4OR3UYlDgpclhJHGRQP-B8dnz2fZJ2_8ye-hyRyNpOfDxjx28VRFt0nHlj6PIlQ8v1WpGMNFMi_bG1scxt2ZOFwfNkCly9yQ1gi44kwOxVkEpTqPcPS3Se3IyOWlnD-OdeRoYptSHsiXdX5C2raQjiD_X8xBjxqlEb_1daOA1m48lUnypyzjDupJbBZpD6aIUTpLnzbOmXk_X8ZavOmomDoofo1DIwB1KGWE4oJUZ3i8c3g_YxqPX3NPwoKtbGV0ZLTDySEfaMhisSyvjB9T2HzyAEfhl2EFVe33eV1OB_pQicXeyCo7DnnMQfXMwQQw-tVt1VD5Z1I3POd-akZc-z2LLTguJ1gqTS5Zr-n0dP2CsXGavAio2YmJzUQV1uLQ4fcvbqidUJ4QcG5q5UmZSOZkBvFFH-tjovNRT29redy8