DELETE http://localhost:8000/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODYzMjE0NDgsIlRva2VuVHlwZSI6ImF1dGhlbnRpY2F0ZV9vbmx5IiwiSUQiOiIiLCJDdXN0b21lckluZm8iOnsiaWQiOiI2YTc5MTY4YjBjZjU3MDIwYjIwOTE5ZDQiLCJuYW1lIjoiQXppeiBBbC1Tb3VmaSIsImVtYWlsIjoiYXppekBleGFtcGxlLmNvbSJ9fQ.GbFWQqTX14C-OYY3z0Gra71aBVpMGw-7XYa53kj7nsAaHSdj4x6IU7EdylnDlzwox-u8lRNKH7SYI9TEBDWV-ViP0wRnf_quErVUuDeQZKEGLYuha4E9LrMvpjj7DXTaYyj7TnRhhfYAaRCwcMMbsggoRTa_qDwGQVc9403q6HmNv4UlTrc4je7rUznD_4TX3J824Tmfq1BVyejD86awOktBNe4FWu-XybKYYYfWZ0cgqrNX98X2xr7g0shvC3xNUOilMdGLQOz4rnIoic4FCE475fFvBhruJv5U86jj9_ihH_RUUW4GbUR5nXaADuME9hWDtRGCRlVlZ7e8uGELRjI9rjNIydzoF5ujoWcaxEHWYw24neLKmgWKNDxLPgfZiPEyraC4rfaAUvldQn90dzNY61RKsgkx1ABrNP2WiuQDdEo3PvFmKvgQXfdD71hPX636CLB9pPIUHYoMGNCqwG5_BbYXGYZ0bctrsovZjd_S3J0yjlIAWYR5SifI1wGdkjYcgf31fAePyKN_welEOSM6tpaA94kHHI5sXdGviyZgLpcQAvii56iGfNaCx9KBUuKKPNAuNtwqe6uio4AdVlijCmk2LCJDI_51DCfF-CFE4niFvp9vlYf4yOWYIv-ki0_A0lPviY3KS8kO6PDaPMXBFoJd539B1bkldQJz-Yw